services:
  app:
    build:
      context: ..
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
       - ..:/usr/local/src
    env_file:
      - envs/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db-data:
